AREA PROGRAM, CODE,READONLY 
 ENTRY
MAIN
 LDR R0, =0x00000000; SOURCE MEMORY LOCATION
 LDR R1, =0x00000100; DESTINATION MEMORY LOCATION
 LDM R0!, {R2-R5}; COPIES CONTINUOSLY FROM EXTERNAL TO R2 TO R5
 STM R1!, {R2-R5}; COPIES CONTINUOSLY FROM R2 TO R5 TO DESTINATION  
 END
 
 ;NOTES
 ; ! is used in line 6 for pointer updation, else 
 ; same value will be updated in all registers(R0 - R15)

  AREA PROGRAM, CODE,READONLY 
 ENTRY
MAIN
 LDR R0, =0x00000000; SOURCE MEMORY LOCATION
 LDR R1, =0x000000F0; DESTINATION MEMORY LOCATION
 LDMIB R0!, {R2-R5}; COPIES CONTINUOSLY FROM EXTERNAL TO R2 TO R5
 STMIB R1!, {R2-R5}; COPIES CONTINUOSLY FROM R2 TO R5 TO DESTINATION  
 END 

 	AREA PROGRAM, CODE,READONLY 
	ENTRY
MAIN
	LDR R0, =0x00000000; SOURCE MEMORY LOCATION
	LDR R1, =0x00000100; DESTINATION MEMORY LOCATION
	MOV R2, #4; 4 LOCATIONS FOR 4 WORDS 
FOR LDR R3, [R0], #4; MOVE THE RESPECTIVE VALUE TO R3
	STR R3, [R1], #4; STORE R3 TO THE RESPECTIVE LOCATION 
	SUBS R2,R2,#1; DECREMENT THE COUNTER
	BNE FOR; IF NOT ZERO REPEAT THE LOOP
	END 